name: Lint and Test Rust

on:
  push:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Run clippy and test
      run: |
        cargo clippy --all
        cargo test --all
